export const clientRoutes = [
  { path: '/', name: 'home', label: 'Accueil', status: 'v1' },
  { path: '/shop', name: 'shop', label: 'Boutique Manuelle', status: 'v1' },
  { path: '/shop/popular', name: 'top-products', label: 'Produits Populaires', status: 'v1' },
  { path: '/shop/last-order', name: 'last-order', label: 'Dernière Commande', status: 'v1' },
  { path: '/assistant', name: 'assistant', label: 'Mode Assisté', status: 'v1' },
  { path: '/cart', name: 'cart', label: 'Panier & Checkout', status: 'v1' },
  { path: '/order/:id', name: 'order-tracking', label: 'Suivi Commande', status: 'v1' },
  { path: '/profile', name: 'profile', label: 'Profil', status: 'v1' },
  { path: '/profile/addresses', name: 'addresses', label: 'Adresses', status: 'v1' },
  { path: '/profile/orders', name: 'order-history', label: 'Historique Commandes', status: 'v1' },
  { path: '/auth', name: 'auth', label: 'Connexion', status: 'v1' },
  { path: '/register', name: 'register', label: 'Inscription', status: 'v1' },
  { path: '/contact', name: 'contact-store', label: 'Contact Dépanneur', status: 'v1' },
  { path: '/terms', name: 'terms', label: "Conditions d'utilisation", status: 'v1' },
  { path: '/privacy', name: 'privacy', label: 'Confidentialité', status: 'v1' },
  { path: '/accessibility', name: 'accessibility', label: 'Accessibilité', status: 'v1' },
  { path: '/help/voice', name: 'voice-help', label: 'Aide Vocale', status: 'v1' },
  { path: '/pay', name: 'payment', label: 'Paiement en ligne', status: 'later' },
];
