import type { Category, Product } from './catalog';
import type { Customer, Address } from './customer';
import type { Order } from './order';
import type { Delivery, DriverProfile } from './delivery';

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'boissons',
    name: 'Boissons',
    slug: 'boissons',
    description: null,
    imageUrl: null,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tenantId: 'topbrutus-demo',
  },
  {
    id: 'snacks',
    name: 'Snacks Salés',
    slug: 'snacks',
    description: null,
    imageUrl: null,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tenantId: 'topbrutus-demo',
  },
  {
    id: 'epicerie',
    name: 'Épicerie',
    slug: 'epicerie',
    description: null,
    imageUrl: null,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tenantId: 'topbrutus-demo',
  },
];

export const DEMO_PRODUCTS: (Product & { emoji?: string })[] = [
  {
    id: 'coke-2l',
    name: 'Coca-Cola 2L',
    slug: 'coke-2l',
    description: 'Bouteille de 2 litres',
    price: 3.49,
    unit: 'unite',
    imageUrl: null,
    status: 'active',
    availability: 'en_stock',
    stock: 12,
    minStock: 2,
    categoryId: 'boissons',
    displayOrder: 1,
    popular: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tenantId: 'topbrutus-demo',
    emoji: '🥤',
  },
  {
    id: 'doritos-nacho',
    name: 'Doritos Nacho',
    slug: 'doritos-nacho',
    description: 'Sac familial',
    price: 4.99,
    unit: 'unite',
    imageUrl: null,
    status: 'active',
    availability: 'en_stock',
    stock: 8,
    minStock: 2,
    categoryId: 'snacks',
    displayOrder: 2,
    popular: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tenantId: 'topbrutus-demo',
    emoji: '🌮',
  },
  {
    id: 'lait-1l',
    name: 'Lait 2% 1L',
    slug: 'lait-1l',
    description: 'Carton',
    price: 2.99,
    unit: 'unite',
    imageUrl: null,
    status: 'active',
    availability: 'en_stock',
    stock: 5,
    minStock: 2,
    categoryId: 'epicerie',
    displayOrder: 3,
    popular: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tenantId: 'topbrutus-demo',
    emoji: '🥛',
  },
];

export const DEMO_CUSTOMER: Customer = {
  id: 'cust-123',
  firstName: 'Jean',
  lastName: 'Dupont',
  email: 'jean.dupont@example.com',
  phone: '+15145551234',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const DEMO_ADDRESS: Address = {
  id: 'addr-1',
  customerId: 'cust-123',
  label: 'Domicile',
  street: '123 rue Principale, App 4B',
  city: 'Montréal',
  postalCode: 'H2X 1Y6',
  country: 'Canada',
  isDefault: true,
  notes: 'Code de porte: 1234. Laissez à la porte.',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const DEMO_ORDER: Order = {
  id: 'ORD-DEMO-001',
  customerId: 'cust-123',
  addressId: 'addr-1',
  status: 'draft',
  totalAmount: 11.97,
  notes: null,
  items: [
    {
      id: 'item-1',
      orderId: 'ORD-DEMO-001',
      productId: 'coke-2l',
      productName: 'Coca-Cola 2L',
      quantity: 2,
      unitPrice: 3.49,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'item-2',
      orderId: 'ORD-DEMO-001',
      productId: 'doritos-nacho',
      productName: 'Doritos Nacho',
      quantity: 1,
      unitPrice: 4.99,
      createdAt: new Date().toISOString(),
    },
  ],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  tenantId: 'topbrutus-demo',
};

export const DEMO_DRIVERS: DriverProfile[] = [
  { id: 'drv-1', name: 'Alexandre', status: 'available', distanceStr: '2km' },
  { id: 'drv-2', name: 'Béatrice', status: 'busy', distanceStr: '5km' },
];

export const DEMO_DELIVERY: Delivery = {
  id: 'DEL-DEMO-001',
  orderId: 'ORD-DEMO-001',
  status: 'available',
  customerName: 'Jean Dupont',
  customerPhone: '+1 514 555 1234',
  address: '123 rue Principale, App 4B, Montréal, QC H2X 1Y6',
  distance: '2.5 km',
  estimatedTime: '10 mins',
  totalAmount: 11.97,
  notes: 'Code de porte: 1234. Laissez à la porte.',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
