/**
 * Catalogue de démonstration
 * Basé sur DEP-0271 à DEP-0280
 * 8 catégories, 12 produits répartis
 */

import type { Catalog, Category, Product, PopularProduct } from '@depaneuria/types';

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat-001',
    slug: 'freins',
    label: 'Freins',
    parentId: null,
    depth: 0,
    displayOrder: 1,
    isVisible: true,
  },
  {
    id: 'cat-002',
    slug: 'filtres',
    label: 'Filtres',
    parentId: null,
    depth: 0,
    displayOrder: 2,
    isVisible: true,
  },
  {
    id: 'cat-003',
    slug: 'eclairage',
    label: 'Éclairage',
    parentId: null,
    depth: 0,
    displayOrder: 3,
    isVisible: true,
  },
  {
    id: 'cat-004',
    slug: 'batteries',
    label: 'Batteries',
    parentId: null,
    depth: 0,
    displayOrder: 4,
    isVisible: true,
  },
  {
    id: 'cat-005',
    slug: 'pneus',
    label: 'Pneus',
    parentId: null,
    depth: 0,
    displayOrder: 5,
    isVisible: true,
  },
  {
    id: 'cat-006',
    slug: 'huiles',
    label: 'Huiles',
    parentId: null,
    depth: 0,
    displayOrder: 6,
    isVisible: true,
  },
  {
    id: 'cat-007',
    slug: 'bougies',
    label: 'Bougies',
    parentId: null,
    depth: 0,
    displayOrder: 7,
    isVisible: true,
  },
  {
    id: 'cat-008',
    slug: 'essuie-glaces',
    label: 'Essuie-glaces',
    parentId: null,
    depth: 0,
    displayOrder: 8,
    isVisible: true,
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    categoryId: 'cat-001',
    sku: 'FRE-001',
    slug: 'plaquettes-frein-avant',
    label: 'Plaquettes de frein avant',
    brand: 'Brembo',
    description: 'Plaquettes de frein céramique haute performance pour freinage optimal',
    status: 'active',
    variants: [
      {
        id: 'var-001',
        productId: 'prod-001',
        label: 'Jeu de 4 plaquettes',
        unit: 'jeu',
        quantity: 4,
        price: 49.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'FRE-001-JEU4',
      },
    ],
    images: [
      {
        id: 'img-001',
        productId: 'prod-001',
        url: '/demo/plaquettes-frein.webp',
        alt: 'Plaquettes de frein avant Brembo',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['freins', 'plaquettes', 'avant', 'céramique'],
    synonyms: ['pads', 'patins de frein'],
    isPopular: true,
    popularRank: 3,
    displayOrder: 1,
  },
  {
    id: 'prod-002',
    categoryId: 'cat-001',
    sku: 'FRE-002',
    slug: 'disques-frein-avant',
    label: 'Disques de frein avant',
    brand: 'Bosch',
    description: 'Disques de frein ventilés en fonte, diamètre 280mm',
    status: 'active',
    variants: [
      {
        id: 'var-002',
        productId: 'prod-002',
        label: 'Paire de disques 280mm',
        unit: 'paire',
        quantity: 2,
        price: 89.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'FRE-002-280MM',
      },
    ],
    images: [
      {
        id: 'img-002',
        productId: 'prod-002',
        url: '/demo/disques-frein.webp',
        alt: 'Disques de frein avant Bosch',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['freins', 'disques', 'avant', 'ventilés'],
    synonyms: ['rotors'],
    isPopular: true,
    popularRank: 5,
    displayOrder: 2,
  },
  {
    id: 'prod-003',
    categoryId: 'cat-002',
    sku: 'FIL-001',
    slug: 'filtre-huile',
    label: 'Filtre à huile',
    brand: 'Mann-Filter',
    description: 'Filtre à huile haute efficacité pour moteurs essence et diesel',
    status: 'active',
    variants: [
      {
        id: 'var-003',
        productId: 'prod-003',
        label: 'Filtre standard',
        unit: 'unité',
        quantity: 1,
        price: 12.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'FIL-001-STD',
      },
    ],
    images: [
      {
        id: 'img-003',
        productId: 'prod-003',
        url: '/demo/filtre-huile.webp',
        alt: 'Filtre à huile Mann-Filter',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['filtre', 'huile', 'moteur'],
    synonyms: ['oil filter'],
    isPopular: true,
    popularRank: 1,
    displayOrder: 1,
  },
  {
    id: 'prod-004',
    categoryId: 'cat-002',
    sku: 'FIL-002',
    slug: 'filtre-air',
    label: 'Filtre à air',
    brand: 'K&N',
    description: 'Filtre à air sportif lavable et réutilisable',
    status: 'active',
    variants: [
      {
        id: 'var-004',
        productId: 'prod-004',
        label: 'Filtre universel',
        unit: 'unité',
        quantity: 1,
        price: 39.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'FIL-002-UNI',
      },
    ],
    images: [
      {
        id: 'img-004',
        productId: 'prod-004',
        url: '/demo/filtre-air.webp',
        alt: 'Filtre à air K&N',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['filtre', 'air', 'sportif', 'réutilisable'],
    synonyms: ['air filter'],
    isPopular: true,
    popularRank: 4,
    displayOrder: 2,
  },
  {
    id: 'prod-005',
    categoryId: 'cat-003',
    sku: 'ECL-001',
    slug: 'ampoule-h7',
    label: 'Ampoule H7 12V 55W',
    brand: 'Philips',
    description: 'Ampoule halogène H7 longue durée pour phares',
    status: 'active',
    variants: [
      {
        id: 'var-005',
        productId: 'prod-005',
        label: 'Ampoule simple',
        unit: 'unité',
        quantity: 1,
        price: 8.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'ECL-001-H7',
      },
    ],
    images: [
      {
        id: 'img-005',
        productId: 'prod-005',
        url: '/demo/ampoule-h7.webp',
        alt: 'Ampoule H7 Philips',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['éclairage', 'ampoule', 'h7', 'phare'],
    synonyms: ['bulb', 'lampe'],
    isPopular: true,
    popularRank: 2,
    displayOrder: 1,
  },
  {
    id: 'prod-006',
    categoryId: 'cat-003',
    sku: 'ECL-002',
    slug: 'ampoule-led-h7',
    label: 'Ampoule LED H7',
    brand: 'Osram',
    description: 'Ampoule LED H7 haute luminosité, consommation réduite',
    status: 'active',
    variants: [
      {
        id: 'var-006',
        productId: 'prod-006',
        label: 'LED 6000K blanc froid',
        unit: 'unité',
        quantity: 1,
        price: 29.99,
        currency: 'EUR',
        availability: 'faible_stock',
        isDefault: true,
        sku: 'ECL-002-LED6K',
      },
    ],
    images: [
      {
        id: 'img-006',
        productId: 'prod-006',
        url: '/demo/ampoule-led.webp',
        alt: 'Ampoule LED H7 Osram',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['éclairage', 'ampoule', 'led', 'h7'],
    synonyms: ['led bulb'],
    displayOrder: 2,
  },
  {
    id: 'prod-007',
    categoryId: 'cat-004',
    sku: 'BAT-001',
    slug: 'batterie-12v-60ah',
    label: 'Batterie 12V 60Ah',
    brand: 'Varta',
    description: 'Batterie auto 12V 60Ah 540A démarrage à froid',
    status: 'active',
    variants: [
      {
        id: 'var-007',
        productId: 'prod-007',
        label: 'Batterie standard',
        unit: 'unité',
        quantity: 1,
        price: 79.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'BAT-001-60AH',
      },
    ],
    images: [
      {
        id: 'img-007',
        productId: 'prod-007',
        url: '/demo/batterie.webp',
        alt: 'Batterie 12V 60Ah Varta',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['batterie', '12v', '60ah'],
    synonyms: ['battery', 'accumulateur'],
    displayOrder: 1,
  },
  {
    id: 'prod-008',
    categoryId: 'cat-005',
    sku: 'PNE-001',
    slug: 'pneu-195-65-r15',
    label: 'Pneu 195/65 R15',
    brand: 'Michelin',
    description: 'Pneu été haute performance 195/65 R15 91V',
    status: 'active',
    variants: [
      {
        id: 'var-008',
        productId: 'prod-008',
        label: 'Pneu été 91V',
        unit: 'unité',
        quantity: 1,
        price: 69.99,
        currency: 'EUR',
        availability: 'sur_commande',
        isDefault: true,
        sku: 'PNE-001-195',
      },
    ],
    images: [
      {
        id: 'img-008',
        productId: 'prod-008',
        url: '/demo/pneu.webp',
        alt: 'Pneu 195/65 R15 Michelin',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['pneu', 'été', '195/65', 'r15'],
    synonyms: ['tire', 'tyre'],
    displayOrder: 1,
  },
  {
    id: 'prod-009',
    categoryId: 'cat-006',
    sku: 'HUI-001',
    slug: 'huile-moteur-5w30',
    label: 'Huile moteur 5W30',
    brand: 'Castrol',
    description: 'Huile moteur synthétique 5W30 5L',
    status: 'active',
    variants: [
      {
        id: 'var-009',
        productId: 'prod-009',
        label: 'Bidon 5L',
        unit: 'bidon',
        quantity: 1,
        volume: '5L',
        price: 44.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'HUI-001-5L',
      },
    ],
    images: [
      {
        id: 'img-009',
        productId: 'prod-009',
        url: '/demo/huile-moteur.webp',
        alt: 'Huile moteur 5W30 Castrol',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['huile', 'moteur', '5w30', 'synthétique'],
    synonyms: ['oil', 'motor oil'],
    displayOrder: 1,
  },
  {
    id: 'prod-010',
    categoryId: 'cat-007',
    sku: 'BOU-001',
    slug: 'bougies-allumage',
    label: 'Bougies d\'allumage',
    brand: 'NGK',
    description: 'Bougies d\'allumage iridium longue durée',
    status: 'active',
    variants: [
      {
        id: 'var-010',
        productId: 'prod-010',
        label: 'Jeu de 4 bougies',
        unit: 'jeu',
        quantity: 4,
        price: 32.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'BOU-001-JEU4',
      },
    ],
    images: [
      {
        id: 'img-010',
        productId: 'prod-010',
        url: '/demo/bougies.webp',
        alt: 'Bougies d\'allumage NGK',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['bougies', 'allumage', 'iridium'],
    synonyms: ['spark plugs'],
    displayOrder: 1,
  },
  {
    id: 'prod-011',
    categoryId: 'cat-008',
    sku: 'ESS-001',
    slug: 'balais-essuie-glace',
    label: 'Balais d\'essuie-glace',
    brand: 'Bosch',
    description: 'Paire de balais d\'essuie-glace 55cm',
    status: 'active',
    variants: [
      {
        id: 'var-011',
        productId: 'prod-011',
        label: 'Paire 55cm',
        unit: 'paire',
        quantity: 2,
        price: 24.99,
        currency: 'EUR',
        availability: 'en_stock',
        isDefault: true,
        sku: 'ESS-001-55CM',
      },
    ],
    images: [
      {
        id: 'img-011',
        productId: 'prod-011',
        url: '/demo/essuie-glace.webp',
        alt: 'Balais d\'essuie-glace Bosch',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['essuie-glace', 'balais'],
    synonyms: ['wiper blades'],
    displayOrder: 1,
  },
  {
    id: 'prod-012',
    categoryId: 'cat-006',
    sku: 'HUI-002',
    slug: 'liquide-refroidissement',
    label: 'Liquide de refroidissement',
    brand: 'Total',
    description: 'Liquide de refroidissement -25°C 2L',
    status: 'active',
    variants: [
      {
        id: 'var-012',
        productId: 'prod-012',
        label: 'Bidon 2L',
        unit: 'bidon',
        quantity: 1,
        volume: '2L',
        price: 14.99,
        currency: 'EUR',
        availability: 'rupture',
        isDefault: true,
        sku: 'HUI-002-2L',
      },
    ],
    images: [
      {
        id: 'img-012',
        productId: 'prod-012',
        url: '/demo/liquide-refroidissement.webp',
        alt: 'Liquide de refroidissement Total',
        size: 'medium',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    tags: ['liquide', 'refroidissement', 'antigel'],
    synonyms: ['coolant', 'antifreeze'],
    displayOrder: 2,
  },
];

export const DEMO_POPULAR_PRODUCTS: PopularProduct[] = [
  { productId: 'prod-003', rank: 1, period: '30j', orderCount: 156 }, // Filtre à huile
  { productId: 'prod-005', rank: 2, period: '30j', orderCount: 142 }, // Ampoule H7
  { productId: 'prod-001', rank: 3, period: '30j', orderCount: 128 }, // Plaquettes frein
  { productId: 'prod-004', rank: 4, period: '30j', orderCount: 98 }, // Filtre à air
  { productId: 'prod-002', rank: 5, period: '30j', orderCount: 87 }, // Disques frein
];

export const DEMO_CATALOG: Catalog = {
  categories: DEMO_CATEGORIES,
  products: DEMO_PRODUCTS,
  popularProducts: DEMO_POPULAR_PRODUCTS,
};
